//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWQuotation
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWQuotEntities : DbContext
    {
        public SWQuotEntities()
            : base("name=SWQuotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ProductImg> tbl_ProductImg { get; set; }
        public virtual DbSet<tbl_ProductPrice> tbl_ProductPrice { get; set; }
        public virtual DbSet<tbl_Products> tbl_Products { get; set; }

        public System.Data.Entity.DbSet<SWQuotation.Models.Product> Products { get; set; }
    }
}
